Cargo.toml
src/de.rs
src/ser.rs
tests/enum.rs

Enums are serialized as strings or arrays. The example shows
how an enum with some values is serialized.
```
enum MyEnum {
A, // serialized as "A"
B(u8), // serialized as ["B", 42]
C(u8, bool), // serialized as ["C", 43, false]
D { x: u8, y: u8 }, // serialized as ["D", {"x": 2, "y": 3}]
}
```
Closes #7

Implement enum serialization and deserialization.

---

src/de.rs
tests/de.rs
tests/enum.rs

This feels a bit gross - is there a nicer way of handling stop words?
Closes #24

Fix handling of variable length maps and lists

---

src/lib.rs
src/value.rs
tests/de.rs
tests/ser.rs

Rust's `HashMap`'s iteration order is non-deterministic, meaning deserializing into `Value` and then serializing has a non-deterministic output. This PR changes that by storing a `Value::Object` as a `BTreeMap`, the same way `serde_json` does it. This is a [breaking-change].
Note that this PR does not preserve the order of incoming CBOR, it merely makes sure that the output order is always the same. `serde_json` has an optional `preserve_order` feature using [linked-hash-map](https://crates.io/crates/linked-hash-map) which would need to be implemented to reach parity with `serde_json`.

Change Value::Object to BTreeMap

---

src/de.rs
src/error.rs

Another attempt to fix #39. Looks easy. I'm not sure about initial vector capacity, but otherwise patch is quite simple.
Note: serde itself caps `size_hint` to 4096 when serializing (i.e. doesn't allocate more than 4096 items up front)

Got rid of MAX_SEQ_LEN (fixes #39)

---

.travis.yml
Cargo.toml
src/de.rs
src/error.rs
src/lib.rs
src/read.rs
src/ser.rs
src/value.rs
tests/std_types.rs

This commit consists of a rewrite of basically all of the serialization
and deserialization logic. The API and internals are based heavily off
of serde_json, in particular, the error type and support for borrowed
deserialization. The deserialization logic is now based off of the tag
byte lookup table described in appendix B of RFC 7049. It's a bit more
verbose, but compiles down to a jump table so there should be some
decent performance benefits in deserialization. It should also resolve
some longstanding correctness issues with deserialization of indefinite
length maps and sequences. The packed encoding can now properly handle
conditionally skipped fields and doesn't need special logic on the
deserialization side due to new serde features.
Closes #37
Closes #36
Closes #32
Closes #31

Major rewrite

---

fuzz/.gitignore
fuzz/Cargo.toml
fuzz/appendix_a.json
fuzz/fuzz_targets/from_reader.rs
fuzz/fuzz_targets/from_slice.rs
fuzz/make_corpus.py

These found the issues fixed in https://github.com/pyfisch/cbor/pull/43/commits/6d23f781cbef0f99b27b4899e3053561d837f99e and https://github.com/pyfisch/cbor/pull/43/commits/8f0079129c6a4f7232761ffc3de452c9a67c81ae.
I've also included a script to initialize a corpus based off of the reference examples in Appendix A of the RFC. The fuzzer appears to do ~50% better with coverage staring off of that base rather than nothing.

Add fuzz targets for from_slice and from_reader

---

src/ser.rs
tests/ser.rs

Closes #51
BREAKING CHANGE: This results in a different serialization
for common types e.g. Ipv4Addr.

Set Serializer is_human_readable to false.

---

src/de.rs
src/ser.rs
tests/ser.rs

Add failing test and fix #57 by setting Deserializer's `is_human_readable` to `false` to match `Serializer`.

Fix roundtrip (de)serialization

---

src/lib.rs
tests/ser.rs

CBOR byte strings are much more efficient than generic arrays.  Also,
add tests for encoding CBOR's various fixed-width byte string types.
Fixes #53

Document using serde_bytes with CBOR byte strings

---

src/read.rs
tests/de.rs

These patches are by-catch of my work on #79, but should can stand on their own; in summary:
* Add more test cases for indefinite length strings (to catch what I think would be the most likely to go wrong with the following changes)
* Simplify `.read_into()` by using a provided method of the Read trait that does mostly the same (what's left is EOF error wrapping)
* In `.read()`, use [`Read::take()`](https://doc.rust-lang.org/stable/std/io/trait.Read.html#method.take) (with [`Read::by_ref()`](https://doc.rust-lang.org/stable/std/io/trait.Read.html#method.by_ref) as in its example to keep the original reader in place) to directly put the read data into the buffer vector without zeroing out a fresh area before
I haven't run any benchmarks on them, but I expect the read_into change to result …

IoReader enhancements

---

src/de.rs
src/lib.rs
src/ser.rs
tests/enum.rs
tests/ser.rs

Since enums are part of the Rust language but not part of the CBOR or JSON spec, each serializer has to make a choice how to encode them. 
serde_cbor chose `["Variant", items..]` while serde_json chose `{"Variant": item}` or `{"Variant": [items..]}`. Although this is immaterial when passing data between Rust programs, it becomes visible if `Values` are used, or when data is passed between Rust and other languages.
This turned out to be a problem for me when I tried to migrate a communicating pair of Python and Rust programs from JSON to CBOR, as assumptions about the encoding of enums had already become buried throughout the Python code.
This pull request adds the option (default false) to encode enums in the serde_json way and adds support for automatically decoding enums from either …

Adds the option to encode enums as 1-key maps.

---

.travis.yml
src/de.rs
src/lib.rs
src/read.rs
tests/de.rs
tests/std_types.rs

This PR describes an idea of how to one might continue after #80, and one answer to the question of whether `scratch_offset` can go away there.
The meat of this PR is 86a51c3762d7daabc214f3621e0d63ed8cd91b4f, 18e254623a39c0c4b0fb69f13181a18f37c9ea70 and 9e123f7cdb4f9492e922c6af72fe314dc3f7b148 (there's a few before because I can't create a PR in github that's based on another PR) which may also make sense to read as a cumulative diff; between them, there is 6fa55802f6a1ae7ce34291ce6aa107a4d6981476 that describes a possible application, and then interfacing and test coverage.
What the patch does is to move the scratch buffer from the deserializer to the the Read trait; each reader can manage a buffer as it seems fit. The Read trait methods change a bit:
* read() now always returns a slice, …

[WIP] Move scratch buffers into readers

---

examples/readme.rs
src/de.rs
src/error.rs
src/read.rs

While work on #79 was set back by the canonicalization changes (which introduced quite some internal allocation), I'd like to propose a few next steps here for inclusion in the next-version branch.
* 39125f4f0335ac5502db8778f61c4ca8acda1df5 is a renaming step after #81 (originally proposed to happen after review was through to make it easier to follow through the code changes in https://github.com/pyfisch/cbor/pull/81#issuecomment-447261360 -- anyway, should be done as the current name is slightly misleading).
* 0818e2f719b5e9f8e386763a805394b668716d5d just removes a level of needless heap-allocation that's contained within the error module
* 690483435d76ab3d5c77359b638f7c09be6d1cec switches from using std to core wherever feasible (became less of an issue in 2018 edition with the `extern …

no_std: more preparatory steps

---

src/error.rs

Remove the implementation of the now-deprecated description method, and
implement source rather than cause.
Closes #94

Update Error impl

---

.cargo/config
.gitignore
.travis.yml
Cargo.toml
src/de.rs
src/error.rs
src/lib.rs
src/read.rs
src/ser.rs
src/write.rs
tests/bennofs.rs
tests/canonical.rs
tests/de.rs
tests/enum.rs
tests/ser.rs
tests/std_types.rs
tests/value.rs

Resolves #79.
This builds on the efforts of @chrysn to implement `no_std` support. It also introduces a few things I needed when developing an embedded application based on this crate.
* Adds a default `std` feature that can be disabled for `no_std` support
* Introduction of a local `Write` trait similar to the existing `Read`, as `std::io::Write` is not available in core.
* `SliceReadFixed`, similar to `SliceRead` but using a mutable slice as a scratch buffer. This is useful in `no_std` environments when the input slice is immutable (so `MutSliceRead` is off the table).
* A new feature `unsealed_read_write` (disabled by default) becomes available, which unseals the `Read` and `Write` trait. This is useful in `no_std` to implement `Read` on a custom `File` type.
the methods …

[WIP] no_std support

---

src/de.rs
src/error.rs
src/ser.rs
tests/std_types.rs

Serde can represent negative numbers up
to -2^64 while an i64's minimum value
is -2^63-1. For this reason these
numbers are now stored as i128.
For symmetry u128 is added.
Note that no numbers beyond +/- 2^64
can be expressed in CBOR and will raise
an error.

Implement ser/de for 128 bit numbers

---

src/de.rs
src/lib.rs
src/read.rs
tests/de.rs

When trying to parse fido2 (ctap2) responses from token,
slices are packed together, cbor encoded data may be followed
by other type of data.
This patch introduces a new `byte_offset` method that would
return the position of the reader.
Based on suggestions of @dtolnay. Superseed #100.

Support deserializing from mixed slices.

---

src/de.rs

When iterating over the input stream during deserializtion, we have no way to get the data size in the stream. This function can help us a little about that.
#110

Add byte_offset() method for StreamDeserializer.

---

Cargo.toml
src/lib.rs
tests/de.rs
tests/ser.rs
tests/std_types.rs

It caused build problems because of optional features.
Change some tests for byte strings.
Remove failing tests I believe to be redundant.
cc @baloo

Remove serde-bytes dev-dependency

---

src/ser.rs
tests/bennofs.rs
tests/enum.rs
tests/ser.rs
tests/std_types.rs

This matches other serde formats.
Directly set options on Serializer.
Remove rarely used to_* methods.
Closes #85

Serialize enums as maps by default

---

tests/de.rs

Test format generated by 0.9 and 0.10 for enum types and pass try them through `accept_standard_enums` and `accept_legacy_enums` options.
See #119 for details

Test deserializer options

---

src/error.rs

When building cbor with no-std, I get the following warning:
```
warning: variant is never constructed: `Io`
--> cbor/src/error.rs:271:5
|
271 |     Io,
|     ^^
|
= note: #[warn(dead_code)] on by default
```

no-std: Fixup warning on dead code

---

tests/de.rs

fixes #127 
This is merely a testcase for the issue reported in #127, but it looks fixed already and I implemented the test. So I figured I should commit it.

test for ipaddr serialization/deserialization

---

src/value/ser.rs

Fixes #136.
I hope this can go into 0.10.1 soon.

Correctly set value::Serializer's is_human_readable

---

.travis.yml

Before, if the `clippy` check would fail `exit 0` would be called which exited the test script. This meant that all subsequent steps would be skipped and the _build would pass_.
Now instead of exiting the test script we just make sure that the script always return a zero exit code.

Don't abort build sucessfully when clippy fails

---

.travis.yml
Cargo.toml
src/de.rs
src/lib.rs
src/read.rs
src/ser.rs
src/write.rs

We implement `serde_cbor::to_vec()` and `serde_cbor::from_slice()` in a `no_std` environment to simplify serialization. For this we use `alloc::vec::Vec`.

Implement 'to_vec' and 'from_slice' for no_std

---

.travis.yml

Travis CI currently says " Could not parse pyfisch/cbor/.travis.yml"

Revert .travis.yml to old version

---

src/de.rs
tests/de.rs

In the deserializer decrement the remaining depth
each time a tagged value is encountered to prevent
stack overflows caused by this recursion.
Small malicious input can cause this overflow,
therefore it is considered to be a security issue.
I'd like to thank Eric Rafaloff at Trail of Bits,
who discovered this issue during a code review,
for reporting it.
Add a test case.

Prevent stack overflow from nested tags

---

src/read.rs

Implement the Offset trait for both types.
Do not implement Offset for MutSliceRead as the
offset may change.
closes #158
@baloo Would you take a look?

Enable byte_offset for IoRead and SliceReadFixed

---

tests/canonical.rs
tests/value.rs

`an_array.into_iter()` currently just works because of the autoref
feature, which then calls `<[T] as IntoIterator>::into_iter`. But
in the future, arrays will implement `IntoIterator`, too. In order
to avoid problems in the future, the call is replaced by `iter()`
which is shorter and more explicit.
A crater run showed that your crate is affected by a potential future 
change. See https://github.com/rust-lang/rust/pull/65819 for more information.

Use `slice::iter` instead of `into_iter` to avoid future breakage

---

Cargo.toml
src/de.rs
src/ser.rs

This removes the `byteorder`-dependency, which is not strictly needed since 1.32; the change does bump the minimum rust version, though. IMHO this is worth losing `byteorder`, which gets pulled in a lot via `cbor`.

Remove byteorder-dependency
